name: SOuthwest practice

on:
  push:
    branches: [ master ]

jobs:
  file-check:
    runs-on: ubuntu-latest
    steps:
      - name: baggage-tracking
        run:  test -f baggage-tracker.log && echo "Found " ||exit 1
