name: SOuthwest practice

on:
  push:
    branches: [ master ]
env:
  AIRLINE: "SOUTHWEST AIRLINES"
  LOG_FILE: "baggage-tracker.log"

jobs:
  file-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Print airline
        run: echo "Checking $AIRLINE  systems..."

      - name: baggage-tracking
        run:  test -f $LOG_FILE  && echo "Found $LOG_FILE" ||exit 1
