name: secrets pipeline

on:
  push:
    branches: [ master ]

env:
  MY_SECRET: ${{ secrets.SOUTHWEST_KEY }}

jobs:
  testing-secret:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v4

      - name: secret-step
        run: echo "key is ready: $MY_SECRET"


